cloud:
  aws:
    region:
      static: us-east-1
      auto: false
    stack:
      auto: false
    credentials:
      access-key: 
      secret-key: 
    endpoint:
      uri: https://sqs.us-east-1.amazonaws.com/394715477709/natan-queue
